### ISSUE TITLE
Week 1 Feedback

### ISSUE THREAD

**Issue by chris-graf** [kmahajan1/kmahajan1.github.io#1]
Hey Kunal, I checked out your challenges for the second bit of feedback in the "Get to Know Your Cohort" challenge. Here are some thoughts:
### Blog

I was impressed by the HTML. I would change the **background color**, because the dark grey makes me expect some sort of screen dialogue or prompt, such as when a site asks you to log in or check a box before accessing the content.
### Reflections

I found some of your earlier reflections difficult to read, because the markdown files were not formatted with line breaks or paragraphs.

**Comment by kmahajan1** [comment]
Thank you for your feedback Chris, appreciate it and will make said changes to reflect your advice!
